### PR TITLE
Reformatting TDM for consistency

### PR DESCRIPTION
**Pull request by RuixiongHu**

### CODE REVIEW

**Comment by RuixiongHu** [comment]
Reformatting TDM and please let me know if there's any problem

**Comment by bartgol** [comment]
What are we going to do with this PR, now that master has undergone substantial changes (including pruning of lots of packages)?

Is RPI doing their own fork off of the tag @ikalash created? If so, maybe the PR should be migrated to that fork?

@ikalash what are your thoughts?

**Comment by ikalash** [comment]
Oh...  this PR was never merged into master?  I somehow missed that.  I would say it should go into the RPI/USC fork, once that's up, yes.  I hope it's not too hard to recreate the PR.  I think there aren't a lot of files involved, so it shouldn't be.

**Comment by bartgol** [comment]
Ok, then I guess we can close the PR.

@RuixiongHu, let us know if there are issues creating the PR on the RPI/USC fork.

**Pull request closed without merging**
