### PR TITLE
Switch from AztecOO to Belos in FROSch tests

### PR DESCRIPTION
**Pull request by jewatkins**
@mperego @iyamazaki These tests are currently running on GPU so I'm switching them to Belos.

### CODE REVIEW

**Review by mperego — APPROVED** [review]
Looks good. I took the opportunity to enable adjoint sensitivities in a couple of tests.

**Comment by jewatkins** [comment]
Thanks! I didn't know the adjoint uses the internal tolerance. Good to know.

**Comment by mperego** [comment]
> Thanks! I didn't know the adjoint uses the internal tolerance. Good to know.

Me neither.. until a few weeks ago. That's also why I wanted to add that option. AztecOO works differently.
Also, Belos+Ifpack2+Amesos2 doesn't work.. I need to create an issue.

**Comment by jewatkins** [comment]
> > Thanks! I didn't know the adjoint uses the internal tolerance. Good to know.
> 
> Me neither.. until a few weeks ago. That's also why I wanted to add that option. AztecOO works differently.
> Also, Belos+Ifpack2+Amesos2 doesn't work.. I need to create an issue.

@mperego did you ever create an issue for Belos+Ifpack2+Amesos2 not working? I just ran into this.

**Comment by mperego** [comment]
> > > Thanks! I didn't know the adjoint uses the internal tolerance. Good to know.
> > 
> > 
> > Me neither.. until a few weeks ago. That's also why I wanted to add that option. AztecOO works differently.
> > Also, Belos+Ifpack2+Amesos2 doesn't work.. I need to create an issue.
> 
> @mperego did you ever create an issue for Belos+Ifpack2+Amesos2 not working? I just ran into this.

No. I had sent an email to Siva, and Nathan Ellingwood started looking into it, but we never got to the bottom of it. I tried to see if we could reproduce that in Stratimikos.. but it's a nightmare.

**Comment by jewatkins** [comment]
Maybe we can add an error temporarily on our side just to make sure no one tries it.

**Comment by mperego** [comment]
That's a good idea. Anyway, I'll try to follow on on that

**Pull request merged**
