### PR TITLE
Final Sideset Refactor Cleanup

### PR DESCRIPTION
**Pull request by mcarlson801**
This PR completely removes the old sideset layouts and replaces them with the collapsed sideset layouts. The layouts previously had the `_sideset` temporary suffix to indicate it was a collapsed layout, but now these suffixes have been removed and evaluators have been updated accordingly.

Additionally, all temporary code from problem files has been removed since we can now assume that the collapsed layout is the only layout.

I think the PR that Luca is working on has some sideset related changes so before this PR can go in, we're going to need to coordinate to figure out if the changes are orthogonal to each other and, if not, come up with a plan for consolidating the changes.

Also, I apologize about how big this PR is but I didn't really see any way of breaking it up into smaller chunks. I hope it isn't too much of a bother.

### CODE REVIEW

**Comment by bartgol** [comment]
Regarding the order, feel free to merge this one, I will rebase and deal with conflicts once it's in.

**Comment by bartgol** [comment]
Also, I'm excited about this cleanup. I haven't looked at the diffs, but I suspect it's going to purge a lot of duplicate functions, as well as lots of clunky if statements..

**Comment by mcarlson801** [comment]
> Also, I'm excited about this cleanup. I haven't looked at the diffs (yet), but I suspect it's going to purge a lot of duplicate functions, as well as lots of clunky if statements..

Yeah, lots of red in the diffs for sure. I had a great time slashing all of that clunky code. 😆

I also snuck in a simplification of the CellToSide Kokkos kernels to reduce the bloat in there the same way we did for BasalFrictionCoefficient. Things should be a lot more readable now.

**Review by mperego — APPROVED** [review]
Thanks @mcarlson801, this is great. Feel free to merge this.

**Comment by mperego** [comment]
@mcarlson801 Any reason why you are not merging this?

**Comment by mcarlson801** [comment]
> @mcarlson801 Any reason why you are not merging this?

I wasn't sure if Jerry/Luca wanted to look over it as well. No other reasons though, I'll check in with them and merge today.

**Review by bartgol — APPROVED** [review]
This looks good to merge to me.

**Review by jewatkins — APPROVED** [review]
I just noticed this today and haven't looked at it thoroughly but let's go ahead and get this in. I can look at it later.

**Pull request merged**
