### PR TITLE
Do mesh rebalance only when explicitely requested

### PR DESCRIPTION
**Pull request by mperego**
Addresses issue #590

### CODE REVIEW

**Comment by bartgol** [comment]
Before approving, I want to check why the rebalance is needed for the hydrology tests.

**Comment by mperego** [comment]
> 
> 
> Before approving, I want to check why the rebalance is needed for the hydrology tests. In particular, why is the test working on my laptop _without_ asking for a rebalance.

@bartgol  Any updates on this? It's not  urgent but it would be good to be done with this.

**Comment by bartgol** [comment]
> > Before approving, I want to check why the rebalance is needed for the hydrology tests. In particular, why is the test working on my laptop _without_ asking for a rebalance.
> 
> @bartgol Any updates on this? It's not urgent but it would be good to be done with this.

Sorry, I forgot. Can I do it tomorrow? Got a deadline that I was hoping to clear out today.

**Comment by mperego** [comment]
> 
> 
> > Before approving, I want to check why the rebalance is needed for the hydrology tests. In particular, why is the test working on my laptop _without_ asking for a rebalance.
> 
> @bartgol Any updates on this? It's not urgent but it would be good to be done with this.

Sure, no rush.

**Comment by mperego** [comment]
@bartgol weekly reminder :-)

**Comment by bartgol** [comment]
Ok, I think GmshSTKMeshStruct _does_ need rebalance. The mesh is loaded only on proc 0, and there's no other logic capable of getting a distributed mesh than rebalancing. The IossSTKMeshStruct gets the rebalance/partitioning done on the fly by StkMeshIoBroker (the property `DECOMPOSITION_METHOD` is set in the Io broker, and it seems to be the property that, if set, triggers the decomposition).

So I think it's ok to make it so that Gmsh meshes are always rebalanced. This is currently not achieved, since Gmsh sets 'Use Serial Mesh' to true rather then setting 'Rebalance Mesh' to true. I'm going to make the micro mod, push, then approve the PR.

**Comment by mperego** [comment]
> 
> 
> Ok, I think GmshSTKMeshStruct _does_ need rebalance. The mesh is loaded only on proc 0, and there's no other logic capable of getting a distributed mesh than rebalancing. The IossSTKMeshStruct gets the rebalance/partitioning done on the fly by StkMeshIoBroker (the property `DECOMPOSITION_METHOD` is set in the Io broker, and it seems to be the property that, if set, triggers the decomposition).
> 
> So I think it's ok to make it so that Gmsh meshes are always rebalanced. This is currently not achieved, since Gmsh sets 'Use Serial Mesh' to true rather then setting 'Rebalance Mesh' to true. I'm going to make the micro mod, push, then approve the PR.

OK! Thanks for looking into that and for working on the PR

**Review by bartgol — APPROVED** [review]

**Pull request merged**
