### PR TITLE
Thyra refactor dist param library

### PR DESCRIPTION
**Pull request by bartgol**
This PR focuses mostly the DistributedParameterLibrary. It now stores only Thyra objects (no more Tpetra nor Epetra (which was never there)), and all classes are now aware of this.

In a few places, it was complicated to think about a petra-unaware implementation (see, e.g., `PHAL_GatherScalarNodalParameter_Def.hpp`), so in those places I still cast the parameter to Tpetra (meaning that the dist parameter MUST still be Tpetra under the hood). The goal is to get rid of that assumption, perhaps introducing a few more helper functions in `Albany_[Epetra|Tpetra]ThyraUtils.*pp`. 

Additionally, I started removing some petra stuff from the `Main_Solve*.cpp` files, adding/fixing some helper functions to handle switches (e.g., writeMatrixMarket). These functions are currently guaranteed to work only for the Tpetra build. I'm still in the process of adding Epetra impls. The good news is that if the underlying object is not Tpetra, an exception will be thrown in those helpers missing the Epetra impl, so one will know where/what implementation is missing.

Keep in mind, the goal is to achieve a single albany implementation (no more `Blah.*pp` alongside `BlahT.*pp`), so assumptions about the underlying linear algebra would break the design. But for now, we are ok pushing them down the stack.

The branch is still undergoing testing, so hold off any thought of merging it. But assuming tests pass, it is relatively ready to be merged.

### CODE REVIEW

**Comment by bartgol** [comment]
Base tests (no packages enabled other than demo pdes) pass on my workstation (gcc, openmp). Now I'm turning on all major packages, and some mesh-depends-on features. Tomorrow I'll see if things worked.

**Comment by bartgol** [comment]
I fixed a few bugs that are thyra-work-related. Some tests still fail; some for unrelated reasons (see comment in #61), some because of the thyra refactor (e.g., Schwarz_Cubes).

**Comment by ikalash** [comment]
What happens with the Schwarz_Cubes tests, out of curiosity?

**Comment by bartgol** [comment]
AT `Schwarz_Coupled.cpp:976`, there is a call 

`Teuchos::RCP<Tpetra_Vector const> pTm = Albany::getConstTpetraVector(pT->getVectorBlock(0));`

Unfortunately, the underlying thyra vector is not a `Thyra::TpetraVector`, but it's a `Thyra::DefaultSpmdVector`. The good news is that we don't really need a tpetra vector. We just need to get an ARCP of its values out, so we can use the thyra utils.

This kind of error may be happening in other tests though, so we need to check what's failing for thyra-related reasons.

**Comment by bartgol** [comment]
I finished fixing the branch. The tests pass on my workstation, except for 3 LCM tests (two for FPE reasons, one is getting a complaint from piro

`p=0: *** Caught standard std::exception of type 'std::logic_error' :

 /home/lbertag/workdir/trilinos/trilinos-install/groppello/gcc/debug/develop/include/Piro_TrapezoidRuleSolver_Def.hpp:470:
 
 Throw number = 1
 
 Throw test that evaluated to true: Teuchos::is_null(dec)
 
 Underlying model in trapezoid decorator does not cast to a Piro::TransientDecorator<Scalar, LocalOrdinal, GlobalOrdinal, Node>`

@ikalash I understand you want to get a clean build before merging other PRs. That's fine with me, but if you are going to do anything on the block discretizations side, you should branch off of this branch.

Also, notice I forced-pushed a rebase, so you need to get a fresh copy of the branch.

**Comment by ikalash** [comment]
Hmmm that’s interesting about the failures.  Do the FPEs happen when you build master on your machine?  Which tests have the FPEs?  I can look at that piro error.  I think once the intel builds are back up we can merge this.

**Comment by ikalash** [comment]
Forgot to ask: I'm also interested in which test has the Piro error.

**Comment by bartgol** [comment]
`99% tests passed, 3 tests failed out of 338

Label Time Summary:
CUDA_TEST    =  48.20 sec*proc (3 tests)

Total Test time (real) = 1842.41 sec

The following tests FAILED:
	116 - StaticElasticity3D (Failed)
	117 - StaticElasticity3D_Traction (Failed)
	128 - Dynamics (Failed)`

The first two fail for FPE reasons (I haven't checked the details, I assumed they were related to the LCM FPEs issues). The last one is the one complaining about piro. My trilinos develop installation is aboud 5 weeks old. But I remember this failure also happening long ago (before christmas).

**Comment by ikalash** [comment]
@bartgol : thanks, as I said, I'll pull the branch, build it, and see what happens for me.  I recall that Piro error from before as well,  but I can't remember what happened with that.  Technically the Piro time-integrators are obsolete from the perspective of LCM, so that test could theoretically be disabled; but nonetheless I'd like to understand why the error is happening.

**Comment by ikalash** [comment]
Ok, so I have done some testing of the branch.  

The StaticElasticity3D tests do not FPE for me.  I actually would not expect these tests to be affected by the known FPEs in the material models b/c this is a simple elasticity problem.  

I had the Piro cast error.  The fix is to change line 20 as follows:

```
class ModelEvaluatorT : public Piro::TransientDecorator<ST, LO, Tpetra_GO, KokkosNode> {
```
I guess you were trying to avoid using Tpetra_GO to consolidate things?  Please go ahead and push this fix if it fixes the problem for you and if you agree with it.

**Comment by bartgol** [comment]
Ah, I don't know why I did that. If your fix works, you can push it directly to the branch, no need for me to test it.

**Comment by ikalash** [comment]
Ok, I am going to test the fix on my largest nightly build on my workstation; if everything's good, I'll push my fix,  approve the PR and we can merge it in.  Then we can see what happens with the other nightlies tomorrow morning.  Sound good?

**Comment by ikalash** [comment]
@bartgol : I just pushed my fixes to your branch and tried to test it in my most stringent nightly.  It looks like you didn't try to compile with SCOREC on.  There is a compilation error: 
```
[ 67%] Building CXX object src/LCM/CMakeFiles/LCM.dir/models/ConstitutiveModel.cpp.o
/home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_DiscretizationFactory.cpp: In member function ‘Teuchos::RCP<Albany::AbstractDiscretization> Albany::DiscretizationFactory::createDiscretizationFromInternalMeshStruct(const std::map<int, std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > > >&, const Teuchos::RCP<Albany::RigidBodyModes>&)’:
/home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_DiscretizationFactory.cpp:472:93: error: invalid new-expression of abstract class type ‘Albany::PUMIDiscretization’
                 return Teuchos::rcp(new Albany::PUMIDiscretization(ms, commT, rigidBodyModes));
                                                                                             ^
In file included from /home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_DiscretizationFactory.cpp:34:
/home/ikalash/nightlyCDash/repos/Albany/src/./disc/pumi/Albany_PUMIDiscretization.hpp:16:7: note:   because the following virtual functions are pure within ‘Albany::PUMIDiscretization’:
 class PUMIDiscretization : public APFDiscretization {
       ^~~~~~~~~~~~~~~~~~
In file included from /home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_DiscretizationFactory.hpp:16,
                 from /home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_DiscretizationFactory.cpp:9:
/home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_AbstractDiscretization.hpp:94:42: note: 	‘virtual Teuchos::RCP<Thyra::LinearOpBase<double> > Albany::AbstractDiscretization::createJacobianOp() const’
     virtual Teuchos::RCP<Thyra_LinearOp> createJacobianOp () const = 0;
                                          ^~~~~~~~~~~~~~~~
/home/ikalash/nightlyCDash/repos/Albany/src/disc/Albany_AbstractDiscretization.hpp:109:42: note: 	‘virtual Teuchos::RCP<Thyra::LinearOpBase<double> > Albany::AbstractDiscretization::createOverlapJacobianOp() const’
     virtual Teuchos::RCP<Thyra_LinearOp> createOverlapJacobianOp () const = 0;
                                          ^~~~~~~~~~~~~~~~~~~~~~~
```
in this case.  The fix isn't as simple as adding the createJacobianOp() routine to Albany_PUMIDiscretization.cpp.  Can you please rebuild with SCOREC on to reproduce the problem and fix it?  I'm happy to test again once the fix is pushed.

**Comment by ikalash** [comment]
Other than SCOREC everything is good with this PR - I have tested it in my debug fpe-check build.

**Comment by ikalash** [comment]
@bartgol : here are instructions for how to build Albany with SCOREC:  https://github.com/SNLComputation/Albany/wiki/Building-with-SCOREC .  Recompilation of Trilinos with SCOREC and things like parmetis is required first.

**Comment by bartgol** [comment]
I think I may have gone a step ahead in the branch. I wasn't supposed to work on the discretization returning an operator for the jacobian (rather than its graph). That's more for a later branch (which I'm working on right now). I guess I was thinking ahead, and put the line in while switching from one branch to the other.

If that's ok with you, I'm going to eliminate that method in this PR, and leave that transition to a thyra op for the jacobian for a later PR.

**Comment by ikalash** [comment]
@bartgol : it's fine with me to remove that stuff, so please go ahead.  Once you've done so, I'm happy to test the new code and report the outcome in my most stringent build.  We can merge it: 1.) once I've done that, 2.) provided the xpetra issue preventing Trilinos nightly builds got fixed today, and 3.) after Mauro has tested the PR with MPAS.  We can shoot for getting it merged tomorrow.

**Comment by bartgol** [comment]
Sounds good. I pushed the fix.

**Comment by ikalash** [comment]
Testing now.  It'll take awhile b/c it's a debug build.  I'll let you know the outcome.

**Comment by ikalash** [comment]
@bartgol : Trilinos broke a bunch of our nightlies again last night (sigh...) but I tested this PR last night and everything looked good.  @mperego please let us know when you've tested it with MPAS.  If that's done today, I can check tomorrow that the builds are back to normal, and merge the PR if they are.

**Comment by bartgol** [comment]
@ikalash yeah, I saw your issue. I'm ok waiting for trilinos to fix the issue. I'd just recommend people to hold off pushes to master that may affect files touched by this PR. It is a sizeable PR, which may generate quite a few conflicts otherwise.

**Pull request merged**
