### PR TITLE
Pruning all packages but LandIce and Demo PDEs

### PR DESCRIPTION
**Pull request by mperego**
Performing the changes in Albany described in issue #569.
 - Removed all the folders in src and tests related to LCM, ATO, Aeras, TDM, Tsunami, Catalyst, QCAD, ANISO, MOR, Hydride, SCOREC, APF, PUMI
- Removed the code that was executed only when any of the packages above were enabled.

I did not touch the doc folder including all the dashboards. I guess @ikalash is going to work on that, also based on what nightly tests we want to keep moving on.

### CODE REVIEW

**Comment by mperego** [comment]
@ikalash Do we need the SolutionSniffer? I've seen it's used in Albany Application. For now I kept it, moving it from LCM/utils/ to src/utility/

**Comment by mperego** [comment]
@bartgol We can probably get rid of `MultiSTKFieldContainer`, right? we do not have to do this now.
Also, there are some members of `AbstractDiscretization` that can be removed (e.g. `isExplicitScheme()` ,`getSphereVolume()` and `getLatticeOrientation()`). These are only the ones I noticed while pruning.

**Comment by bartgol** [comment]
> @bartgol We can probably get rid of `MultiSTKFieldContainer`, right? we do not have to do this now.
> Also, there are some members of `AbstractDiscretization` that can be removed (e.g. `isExplicitScheme()` ,`getSphereVolume()` and `getLatticeOrientation()`). These are only the ones I noticed while pruning.

The MultiSTK container _might_ come handy in the future, and it has a somewhat limited maintenance cost (for now). I think we can wait a bit, and if need be do it in a second phase (where we can prune stuff in main Albany folders that is specific to one of the pruned packages).

**Comment by ikalash** [comment]
Regarding ``isExplicitScheme()": I put this in for Aeras as an optimization to efficiently handle the case of explicit dynamics and a diagonal mass matrix.  If we think this case might be useful for ALI, we could keep it.

**Comment by jewatkins** [comment]
Is MultiSTKFieldContainer, isExplicitScheme() tested with DemoPDEs or ALI? If not, I'd probably remove it as it may become stale. We could always add it back in when needed.

**Comment by jewatkins** [comment]
But yeah, I agree, we could remove more in a second phase. Let's get the main chunks out first.

**Comment by ikalash** [comment]
No, ``isExplicitScheme" is not tested in ALI or DemoPDEs.

**Comment by ikalash** [comment]
@lxmota , can you please remind us what SolutionSniffer does?

**Comment by mperego** [comment]
> @lxmota , can you please remind us what SolutionSniffer does?

By the way, it's used only if the solution method is "Transient Tempus" or "Transient Tempus No Piro" AND if DEBUG is defined AND if the Solver option "User Defined Pre/Post Operator" is not set.

**Comment by mperego** [comment]
> 
> But yeah, I agree, we could remove more in a second phase. Let's get the main chunks out first.

I don't think any of those are tested, but we could remove these later. (There are comments saying that they are only used by Aeras or LCM or Peridigm)

**Comment by lxmota** [comment]
@mperego @ikalash The SolutionSniffer is just a wrapper for the NOX Pre and PostOperator feature. It was originally intended to compute the Schwarz convergence criterion, but I found an easier way to do that. And so the SolutionSniffer morphed into a debugging tool to inspect the solution vectors of different subdomains for Schwarz coupling. Hence it's now only defined when DEBUG is on. It can be safely deleted.

**Comment by lxmota** [comment]
Who is in charge of the SNLComputation org (https://github.com/SNLComputation)? I would like to move my Albany fork there so it's not confined to my account.

**Comment by mperego** [comment]
> Who is in charge of the SNLComputation org (https://github.com/SNLComputation)? I would like to move my Albany fork there so it's not confined to my account.

It used to be @gahansen. @ibaned and @kuberry  are admins as well. =

**Comment by agsalin** [comment]
alejandro: Irina, Luca, and I are all owners as well. Would it help you to be one as well, permanently or temporarily?

**Comment by mperego** [comment]
> @mperego @ikalash The SolutionSniffer is just a wrapper for the NOX Pre and PostOperator feature. It was originally intended to compute the Schwarz convergence criterion, but I found an easier way to do that. And so the SolutionSniffer morphed into a debugging tool to inspect the solution vectors of different subdomains for Schwarz coupling. Hence it's now only defined when DEBUG is on. It can be safely deleted.

@ikalash I can go ahead and remove it, if you are fine with that.

**Comment by ikalash** [comment]
I'm ok with removing SolutionSniffer.

**Comment by ibaned** [comment]
I can do administrative things for SNLComputation. However, since SNLComputation owns Albany, I don't think it can also have a fork of Albany. By definition a fork is under someone else's account.

**Comment by mperego** [comment]
> 
> 
> I'm ok with removing SolutionSniffer.

Done. B.t.w. I tested the branch playing with a few option (LandIce on/off, Demo PDEs on/off, Epetra on/off).

**Comment by lxmota** [comment]
@ibaned Thanks! What I proposed was to rename my Albany fork to LCM and move it to SNLComputation, if nobody objects to that.

**Comment by ibaned** [comment]
I can create a repository named LCM and give you control of it to push

**Comment by lxmota** [comment]
@agsalin Thanks! I'm don't think I need to be an admin, since @ibaned would create an LCM repo for me. @ibaned would the new repo keep the commit history?

**Comment by bartgol** [comment]
> @agsalin Thanks! I'm don't think I need to be an admin, since @ibaned would create an LCM repo for me. @ibaned would the new repo keep the commit history?

I think if you could push a branch to that repo, then do a PR. That way the commits _should_ be kept.
If that repo is init-ed as empty, things should be relatively seamless.

**Comment by ikalash** [comment]
@mperego : just FYI - I am testing this PR in some of my nightly builds.  I'll approve it once that's done.

**Comment by mperego** [comment]
> @mperego : just FYI - I am testing this PR in some of my nightly builds. I'll approve it once that's done.

thanks!

**Comment by mperego** [comment]
Thanks all for being so responsive in giving your feedback, and thanks @ikalash for testing it. I'm going to merge it now.

**Pull request merged**
